---
title: "Workshop3"
author: "Hsin-Chieh Tang"
date: "13/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Workshop3

```{r}
# install.packages('skimr')

library(tidyverse)
library(janitor)
library(skimr)

survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

survey%>%head()

survey%>%skim()

survey%>% filter(how_old_are_you== "25-34")

survey%>% filter(how_old_are_you== "25-34" & annual_salary>80000)

survey%>% filter(industry== "Computing or Tech" | annual_salary>80000)

survey%>%top_n(10, annual_salary)

survey%>%arrange(annual_salary)

survey%>%select(how_old_are_you, industry, annual_salary)

survey%>% select(how_old_are_you, industry, annual_salary)%>% filter(how_old_are_you== "25-34" & annual_salary>8000)

#Use rename() function to rename how_old_are _you variable into age_range

#Create a new variable called age by using mutate() and parse_number() function

survey_new<- survey%>% mutate(age=parse_number(how_old_are_you))

#Group the dataset by industry and calculate the average age:

survey_new%>% group_by(industry)%>% summarise(mean_age=mean(age))





```

